#!/usr/bin/env bash
# Vendor third-party Agent Skills declared in external.yml into ./external/,
# recording the exact upstream commit of each in external.lock.
#
# Self-written skills live in ./skills/ and are never touched here. ./external/ is
# git-ignored and fully disposable — re-runnable any time. After vendoring, run
# `just link` to symlink everything into ~/.claude/skills and ~/.codex/skills.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
manifest="$repo_root/external.yml"
ext_dir="$repo_root/external"
lock="$repo_root/external.lock"

[ -f "$manifest" ] || { echo "✗ no external.yml at $manifest"; exit 1; }
command -v git     >/dev/null || { echo "✗ git required"; exit 1; }
command -v python3 >/dev/null || { echo "✗ python3 required"; exit 1; }

mkdir -p "$ext_dir"

# Emit one TAB-separated line per source: repo \t ref \t include1,include2,...
parse_manifest() {
  python3 - "$manifest" <<'PY'
import sys, yaml
doc = yaml.safe_load(open(sys.argv[1])) or {}
for s in doc.get("sources", []):
    repo = s["repo"]
    ref = str(s.get("ref", "main"))
    inc = ",".join(s.get("include", []))
    print(f"{repo}\t{ref}\t{inc}")
PY
}

tmproot="$(mktemp -d)"
trap 'rm -rf "$tmproot"' EXIT

lock_tmp="$lock.tmp"
{
  echo "# external.lock — auto-generated by scripts/vendor.sh; do not edit by hand."
  echo "# Records the exact upstream commit each vendored skill was pulled from."
} > "$lock_tmp"

managed=()
while IFS=$'\t' read -r repo ref inc; do
  [ -n "$repo" ] || continue
  if [ -z "$inc" ]; then
    echo "▸ $repo @ $ref — no include paths, skipping"
    continue
  fi
  echo "▸ $repo @ $ref"
  work="$tmproot/$(echo "$repo" | tr '/:.' '___')"
  git clone --quiet --filter=blob:none --sparse "$repo" "$work"
  IFS=',' read -ra paths <<< "$inc"
  ( cd "$work" \
      && git sparse-checkout set "${paths[@]}" >/dev/null \
      && git checkout --quiet "$ref" )
  sha="$(git -C "$work" rev-parse HEAD)"
  {
    echo ""
    echo "$repo"
    echo "  ref: $ref"
    echo "  commit: $sha"
  } >> "$lock_tmp"
  for p in "${paths[@]}"; do
    src="$work/$p"
    name="$(basename "$p")"
    if [ ! -f "$src/SKILL.md" ]; then
      echo "  ✗ $p — no SKILL.md, skipping"
      continue
    fi
    if [ -d "$repo_root/skills/$name" ]; then
      echo "  ✗ $name — collides with self-written skills/$name, skipping"
      continue
    fi
    rm -rf "${ext_dir:?}/$name"
    cp -R "$src" "$ext_dir/$name"
    managed+=("$name")
    echo "  ✓ $name"
    echo "  skill: $name" >> "$lock_tmp"
  done
done < <(parse_manifest)

# Prune external/ dirs no longer in the manifest (only after a successful run with
# at least one managed skill, so a transient failure never wipes the set).
if [ "${#managed[@]}" -gt 0 ]; then
  for d in "$ext_dir"/*/; do
    [ -d "$d" ] || continue
    name="$(basename "$d")"
    keep=0
    for m in "${managed[@]}"; do [ "$m" = "$name" ] && keep=1 && break; done
    if [ "$keep" -eq 0 ]; then
      rm -rf "$d"
      echo "  – pruned external/$name (not in external.yml)"
    fi
  done
fi

mv "$lock_tmp" "$lock"
echo ""
echo "Vendored ${#managed[@]} skill(s) into external/: ${managed[*]:-none}"
echo "Wrote external.lock. Run 'just link' to symlink into ~/.claude/skills + ~/.codex/skills."
